language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '7'
  - '8'
  - '10'
before_install:
  - npm install -g yarn codecov greenkeeper-lockfile
install:
  - yarn install
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn test -- --verbose
after_script:
  - codecov
  - greenkeeper-lockfile-upload
